name: cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://later.wtf/api/cron?key=$CRON_KEY
        env:
          CRON_KEY: ${{ secrets.CRON_KEY }}
